### ISSUE TITLE
Request for MSN_1.pth Model File

### ISSUE THREAD

**Issue by YOUSEF331535** [Dudujia160918/MSNet#1]
Dear Repository Owner,

I hope this message finds you well. I am writing to inquire about the `MSN_1.pth` model file associated with the MSNet project, which I found in your GitHub repository (https://github.com/Dudujia160918/MSNet).

I am currently working on a project related to [briefly describe your project or area of research/study] and I believe the `MSN_1.pth` model could be immensely beneficial for my work. I have gone through your repository but could not locate this specific model file.

Could you kindly guide how I might access the `MSN_1.pth` model file? If it is available for download or if there are specific instructions to generate it, I would greatly appreciate your assistance pointing me in the right direction.

Thank you very much for your time and for contributing valuable resources to the community. I look forward to your response and any assistance you can provide.

Best regards,
yousef
alyousefy2023@gmail.com

**Comment by Dudujia160918** [comment]
The code and weight files have been updated and are available here:https://pan.baidu.com/s/1Xs_-SpkuXUzjaRWOoTbT_g?pwd=jwez extract code: jwez
